// This file is generated by rust-protobuf 2.27.1. Do not edit
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `torch.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
// const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_27_1;

#[derive(PartialEq,Clone,Default)]
pub struct TorchModelLoadRequest {
    // message fields
    pub session_id: u32,
    pub model_id: i64,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a TorchModelLoadRequest {
    fn default() -> &'a TorchModelLoadRequest {
        <TorchModelLoadRequest as ::protobuf::Message>::default_instance()
    }
}

impl TorchModelLoadRequest {
    pub fn new() -> TorchModelLoadRequest {
        ::std::default::Default::default()
    }

    // uint32 session_id = 1;


    pub fn get_session_id(&self) -> u32 {
        self.session_id
    }
    pub fn clear_session_id(&mut self) {
        self.session_id = 0;
    }

    // Param is passed by value, moved
    pub fn set_session_id(&mut self, v: u32) {
        self.session_id = v;
    }

    // int64 model_id = 2;


    pub fn get_model_id(&self) -> i64 {
        self.model_id
    }
    pub fn clear_model_id(&mut self) {
        self.model_id = 0;
    }

    // Param is passed by value, moved
    pub fn set_model_id(&mut self, v: i64) {
        self.model_id = v;
    }
}

impl ::protobuf::Message for TorchModelLoadRequest {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint32()?;
                    self.session_id = tmp;
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int64()?;
                    self.model_id = tmp;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.session_id != 0 {
            my_size += ::protobuf::rt::value_size(1, self.session_id, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.model_id != 0 {
            my_size += ::protobuf::rt::value_size(2, self.model_id, ::protobuf::wire_format::WireTypeVarint);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if self.session_id != 0 {
            os.write_uint32(1, self.session_id)?;
        }
        if self.model_id != 0 {
            os.write_int64(2, self.model_id)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> TorchModelLoadRequest {
        TorchModelLoadRequest::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint32>(
                "session_id",
                |m: &TorchModelLoadRequest| { &m.session_id },
                |m: &mut TorchModelLoadRequest| { &mut m.session_id },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt64>(
                "model_id",
                |m: &TorchModelLoadRequest| { &m.model_id },
                |m: &mut TorchModelLoadRequest| { &mut m.model_id },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<TorchModelLoadRequest>(
                "TorchModelLoadRequest",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static TorchModelLoadRequest {
        static instance: ::protobuf::rt::LazyV2<TorchModelLoadRequest> = ::protobuf::rt::LazyV2::INIT;
        instance.get(TorchModelLoadRequest::new)
    }
}

impl ::protobuf::Clear for TorchModelLoadRequest {
    fn clear(&mut self) {
        self.session_id = 0;
        self.model_id = 0;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for TorchModelLoadRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for TorchModelLoadRequest {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct TorchModelLoadResponse {
    // message oneof groups
    pub result: ::std::option::Option<TorchModelLoadResponse_oneof_result>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a TorchModelLoadResponse {
    fn default() -> &'a TorchModelLoadResponse {
        <TorchModelLoadResponse as ::protobuf::Message>::default_instance()
    }
}

#[derive(Clone,PartialEq,Debug)]
pub enum TorchModelLoadResponse_oneof_result {
    graph_def(::std::vec::Vec<u8>),
    error(super::error::VaccelError),
}

impl TorchModelLoadResponse {
    pub fn new() -> TorchModelLoadResponse {
        ::std::default::Default::default()
    }

    // bytes graph_def = 1;


    pub fn get_graph_def(&self) -> &[u8] {
        match self.result {
            ::std::option::Option::Some(TorchModelLoadResponse_oneof_result::graph_def(ref v)) => v,
            _ => &[],
        }
    }
    pub fn clear_graph_def(&mut self) {
        self.result = ::std::option::Option::None;
    }

    pub fn has_graph_def(&self) -> bool {
        match self.result {
            ::std::option::Option::Some(TorchModelLoadResponse_oneof_result::graph_def(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_graph_def(&mut self, v: ::std::vec::Vec<u8>) {
        self.result = ::std::option::Option::Some(TorchModelLoadResponse_oneof_result::graph_def(v))
    }

    // Mutable pointer to the field.
    pub fn mut_graph_def(&mut self) -> &mut ::std::vec::Vec<u8> {
        if let ::std::option::Option::Some(TorchModelLoadResponse_oneof_result::graph_def(_)) = self.result {
        } else {
            self.result = ::std::option::Option::Some(TorchModelLoadResponse_oneof_result::graph_def(::std::vec::Vec::new()));
        }
        match self.result {
            ::std::option::Option::Some(TorchModelLoadResponse_oneof_result::graph_def(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_graph_def(&mut self) -> ::std::vec::Vec<u8> {
        if self.has_graph_def() {
            match self.result.take() {
                ::std::option::Option::Some(TorchModelLoadResponse_oneof_result::graph_def(v)) => v,
                _ => panic!(),
            }
        } else {
            ::std::vec::Vec::new()
        }
    }

    // .vaccel.VaccelError error = 2;


    pub fn get_error(&self) -> &super::error::VaccelError {
        match self.result {
            ::std::option::Option::Some(TorchModelLoadResponse_oneof_result::error(ref v)) => v,
            _ => <super::error::VaccelError as ::protobuf::Message>::default_instance(),
        }
    }
    pub fn clear_error(&mut self) {
        self.result = ::std::option::Option::None;
    }

    pub fn has_error(&self) -> bool {
        match self.result {
            ::std::option::Option::Some(TorchModelLoadResponse_oneof_result::error(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_error(&mut self, v: super::error::VaccelError) {
        self.result = ::std::option::Option::Some(TorchModelLoadResponse_oneof_result::error(v))
    }

    // Mutable pointer to the field.
    pub fn mut_error(&mut self) -> &mut super::error::VaccelError {
        if let ::std::option::Option::Some(TorchModelLoadResponse_oneof_result::error(_)) = self.result {
        } else {
            self.result = ::std::option::Option::Some(TorchModelLoadResponse_oneof_result::error(super::error::VaccelError::new()));
        }
        match self.result {
            ::std::option::Option::Some(TorchModelLoadResponse_oneof_result::error(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_error(&mut self) -> super::error::VaccelError {
        if self.has_error() {
            match self.result.take() {
                ::std::option::Option::Some(TorchModelLoadResponse_oneof_result::error(v)) => v,
                _ => panic!(),
            }
        } else {
            super::error::VaccelError::new()
        }
    }
}

impl ::protobuf::Message for TorchModelLoadResponse {
    fn is_initialized(&self) -> bool {
        if let Some(TorchModelLoadResponse_oneof_result::error(ref v)) = self.result {
            if !v.is_initialized() {
                return false;
            }
        }
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.result = ::std::option::Option::Some(TorchModelLoadResponse_oneof_result::graph_def(is.read_bytes()?));
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.result = ::std::option::Option::Some(TorchModelLoadResponse_oneof_result::error(is.read_message()?));
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let ::std::option::Option::Some(ref v) = self.result {
            match v {
                &TorchModelLoadResponse_oneof_result::graph_def(ref v) => {
                    my_size += ::protobuf::rt::bytes_size(1, &v);
                },
                &TorchModelLoadResponse_oneof_result::error(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
                },
            };
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if let ::std::option::Option::Some(ref v) = self.result {
            match v {
                &TorchModelLoadResponse_oneof_result::graph_def(ref v) => {
                    os.write_bytes(1, v)?;
                },
                &TorchModelLoadResponse_oneof_result::error(ref v) => {
                    os.write_tag(2, ::protobuf::wire_format::WireTypeLengthDelimited)?;
                    os.write_raw_varint32(v.get_cached_size())?;
                    v.write_to_with_cached_sizes(os)?;
                },
            };
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> TorchModelLoadResponse {
        TorchModelLoadResponse::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_singular_bytes_accessor::<_>(
                "graph_def",
                TorchModelLoadResponse::has_graph_def,
                TorchModelLoadResponse::get_graph_def,
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_message_accessor::<_, super::error::VaccelError>(
                "error",
                TorchModelLoadResponse::has_error,
                TorchModelLoadResponse::get_error,
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<TorchModelLoadResponse>(
                "TorchModelLoadResponse",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static TorchModelLoadResponse {
        static instance: ::protobuf::rt::LazyV2<TorchModelLoadResponse> = ::protobuf::rt::LazyV2::INIT;
        instance.get(TorchModelLoadResponse::new)
    }
}

impl ::protobuf::Clear for TorchModelLoadResponse {
    fn clear(&mut self) {
        self.result = ::std::option::Option::None;
        self.result = ::std::option::Option::None;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for TorchModelLoadResponse {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for TorchModelLoadResponse {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct TorchModelUnloadRequest {
    // message fields
    pub session_id: u32,
    pub model_id: i64,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a TorchModelUnloadRequest {
    fn default() -> &'a TorchModelUnloadRequest {
        <TorchModelUnloadRequest as ::protobuf::Message>::default_instance()
    }
}

impl TorchModelUnloadRequest {
    pub fn new() -> TorchModelUnloadRequest {
        ::std::default::Default::default()
    }

    // uint32 session_id = 1;


    pub fn get_session_id(&self) -> u32 {
        self.session_id
    }
    pub fn clear_session_id(&mut self) {
        self.session_id = 0;
    }

    // Param is passed by value, moved
    pub fn set_session_id(&mut self, v: u32) {
        self.session_id = v;
    }

    // int64 model_id = 2;


    pub fn get_model_id(&self) -> i64 {
        self.model_id
    }
    pub fn clear_model_id(&mut self) {
        self.model_id = 0;
    }

    // Param is passed by value, moved
    pub fn set_model_id(&mut self, v: i64) {
        self.model_id = v;
    }
}

impl ::protobuf::Message for TorchModelUnloadRequest {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint32()?;
                    self.session_id = tmp;
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int64()?;
                    self.model_id = tmp;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.session_id != 0 {
            my_size += ::protobuf::rt::value_size(1, self.session_id, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.model_id != 0 {
            my_size += ::protobuf::rt::value_size(2, self.model_id, ::protobuf::wire_format::WireTypeVarint);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if self.session_id != 0 {
            os.write_uint32(1, self.session_id)?;
        }
        if self.model_id != 0 {
            os.write_int64(2, self.model_id)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> TorchModelUnloadRequest {
        TorchModelUnloadRequest::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint32>(
                "session_id",
                |m: &TorchModelUnloadRequest| { &m.session_id },
                |m: &mut TorchModelUnloadRequest| { &mut m.session_id },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt64>(
                "model_id",
                |m: &TorchModelUnloadRequest| { &m.model_id },
                |m: &mut TorchModelUnloadRequest| { &mut m.model_id },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<TorchModelUnloadRequest>(
                "TorchModelUnloadRequest",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static TorchModelUnloadRequest {
        static instance: ::protobuf::rt::LazyV2<TorchModelUnloadRequest> = ::protobuf::rt::LazyV2::INIT;
        instance.get(TorchModelUnloadRequest::new)
    }
}

impl ::protobuf::Clear for TorchModelUnloadRequest {
    fn clear(&mut self) {
        self.session_id = 0;
        self.model_id = 0;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for TorchModelUnloadRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for TorchModelUnloadRequest {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct TorchModelUnloadResponse {
    // message fields
    pub success: bool,
    pub error: ::protobuf::SingularPtrField<super::error::VaccelError>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a TorchModelUnloadResponse {
    fn default() -> &'a TorchModelUnloadResponse {
        <TorchModelUnloadResponse as ::protobuf::Message>::default_instance()
    }
}

impl TorchModelUnloadResponse {
    pub fn new() -> TorchModelUnloadResponse {
        ::std::default::Default::default()
    }

    // bool success = 1;


    pub fn get_success(&self) -> bool {
        self.success
    }
    pub fn clear_success(&mut self) {
        self.success = false;
    }

    // Param is passed by value, moved
    pub fn set_success(&mut self, v: bool) {
        self.success = v;
    }

    // .vaccel.VaccelError error = 2;


    pub fn get_error(&self) -> &super::error::VaccelError {
        self.error.as_ref().unwrap_or_else(|| <super::error::VaccelError as ::protobuf::Message>::default_instance())
    }
    pub fn clear_error(&mut self) {
        self.error.clear();
    }

    pub fn has_error(&self) -> bool {
        self.error.is_some()
    }

    // Param is passed by value, moved
    pub fn set_error(&mut self, v: super::error::VaccelError) {
        self.error = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_error(&mut self) -> &mut super::error::VaccelError {
        if self.error.is_none() {
            self.error.set_default();
        }
        self.error.as_mut().unwrap()
    }

    // Take field
    pub fn take_error(&mut self) -> super::error::VaccelError {
        self.error.take().unwrap_or_else(|| super::error::VaccelError::new())
    }
}

impl ::protobuf::Message for TorchModelUnloadResponse {
    fn is_initialized(&self) -> bool {
        for v in &self.error {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_bool()?;
                    self.success = tmp;
                },
                2 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.error)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.success != false {
            my_size += 2;
        }
        if let Some(ref v) = self.error.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if self.success != false {
            os.write_bool(1, self.success)?;
        }
        if let Some(ref v) = self.error.as_ref() {
            os.write_tag(2, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> TorchModelUnloadResponse {
        TorchModelUnloadResponse::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBool>(
                "success",
                |m: &TorchModelUnloadResponse| { &m.success },
                |m: &mut TorchModelUnloadResponse| { &mut m.success },
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<super::error::VaccelError>>(
                "error",
                |m: &TorchModelUnloadResponse| { &m.error },
                |m: &mut TorchModelUnloadResponse| { &mut m.error },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<TorchModelUnloadResponse>(
                "TorchModelUnloadResponse",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static TorchModelUnloadResponse {
        static instance: ::protobuf::rt::LazyV2<TorchModelUnloadResponse> = ::protobuf::rt::LazyV2::INIT;
        instance.get(TorchModelUnloadResponse::new)
    }
}

impl ::protobuf::Clear for TorchModelUnloadResponse {
    fn clear(&mut self) {
        self.success = false;
        self.error.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for TorchModelUnloadResponse {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for TorchModelUnloadResponse {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct TorchTensor {
    // message fields
    pub data: ::std::vec::Vec<u8>,
    pub size: u64,
    pub owned: u32,
    pub nr_dims: i32,
    pub dims: ::std::vec::Vec<u64>,
    pub field_type: TorchDataType,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a TorchTensor {
    fn default() -> &'a TorchTensor {
        <TorchTensor as ::protobuf::Message>::default_instance()
    }
}

impl TorchTensor {
    pub fn new() -> TorchTensor {
        ::std::default::Default::default()
    }

    // bytes data = 1;


    pub fn get_data(&self) -> &[u8] {
        &self.data
    }
    pub fn clear_data(&mut self) {
        self.data.clear();
    }

    // Param is passed by value, moved
    pub fn set_data(&mut self, v: ::std::vec::Vec<u8>) {
        self.data = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_data(&mut self) -> &mut ::std::vec::Vec<u8> {
        &mut self.data
    }

    // Take field
    pub fn take_data(&mut self) -> ::std::vec::Vec<u8> {
        ::std::mem::replace(&mut self.data, ::std::vec::Vec::new())
    }

    // uint64 size = 2;


    pub fn get_size(&self) -> u64 {
        self.size
    }
    pub fn clear_size(&mut self) {
        self.size = 0;
    }

    // Param is passed by value, moved
    pub fn set_size(&mut self, v: u64) {
        self.size = v;
    }

    // uint32 owned = 3;


    pub fn get_owned(&self) -> u32 {
        self.owned
    }
    pub fn clear_owned(&mut self) {
        self.owned = 0;
    }

    // Param is passed by value, moved
    pub fn set_owned(&mut self, v: u32) {
        self.owned = v;
    }

    // int32 nr_dims = 4;


    pub fn get_nr_dims(&self) -> i32 {
        self.nr_dims
    }
    pub fn clear_nr_dims(&mut self) {
        self.nr_dims = 0;
    }

    // Param is passed by value, moved
    pub fn set_nr_dims(&mut self, v: i32) {
        self.nr_dims = v;
    }

    // repeated uint64 dims = 5;


    pub fn get_dims(&self) -> &[u64] {
        &self.dims
    }
    pub fn clear_dims(&mut self) {
        self.dims.clear();
    }

    // Param is passed by value, moved
    pub fn set_dims(&mut self, v: ::std::vec::Vec<u64>) {
        self.dims = v;
    }

    // Mutable pointer to the field.
    pub fn mut_dims(&mut self) -> &mut ::std::vec::Vec<u64> {
        &mut self.dims
    }

    // Take field
    pub fn take_dims(&mut self) -> ::std::vec::Vec<u64> {
        ::std::mem::replace(&mut self.dims, ::std::vec::Vec::new())
    }

    // .vaccel.TorchDataType type = 6;


    pub fn get_field_type(&self) -> TorchDataType {
        self.field_type
    }
    pub fn clear_field_type(&mut self) {
        self.field_type = TorchDataType::UNUSED;
    }

    // Param is passed by value, moved
    pub fn set_field_type(&mut self, v: TorchDataType) {
        self.field_type = v;
    }
}

impl ::protobuf::Message for TorchTensor {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_bytes_into(wire_type, is, &mut self.data)?;
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.size = tmp;
                },
                3 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint32()?;
                    self.owned = tmp;
                },
                4 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int32()?;
                    self.nr_dims = tmp;
                },
                5 => {
                    ::protobuf::rt::read_repeated_uint64_into(wire_type, is, &mut self.dims)?;
                },
                6 => {
                    ::protobuf::rt::read_proto3_enum_with_unknown_fields_into(wire_type, is, &mut self.field_type, 6, &mut self.unknown_fields)?
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.data.is_empty() {
            my_size += ::protobuf::rt::bytes_size(1, &self.data);
        }
        if self.size != 0 {
            my_size += ::protobuf::rt::value_size(2, self.size, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.owned != 0 {
            my_size += ::protobuf::rt::value_size(3, self.owned, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.nr_dims != 0 {
            my_size += ::protobuf::rt::value_size(4, self.nr_dims, ::protobuf::wire_format::WireTypeVarint);
        }
        for value in &self.dims {
            my_size += ::protobuf::rt::value_size(5, *value, ::protobuf::wire_format::WireTypeVarint);
        };
        if self.field_type != TorchDataType::UNUSED {
            my_size += ::protobuf::rt::enum_size(6, self.field_type);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if !self.data.is_empty() {
            os.write_bytes(1, &self.data)?;
        }
        if self.size != 0 {
            os.write_uint64(2, self.size)?;
        }
        if self.owned != 0 {
            os.write_uint32(3, self.owned)?;
        }
        if self.nr_dims != 0 {
            os.write_int32(4, self.nr_dims)?;
        }
        for v in &self.dims {
            os.write_uint64(5, *v)?;
        };
        if self.field_type != TorchDataType::UNUSED {
            os.write_enum(6, ::protobuf::ProtobufEnum::value(&self.field_type))?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> TorchTensor {
        TorchTensor::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                "data",
                |m: &TorchTensor| { &m.data },
                |m: &mut TorchTensor| { &mut m.data },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                "size",
                |m: &TorchTensor| { &m.size },
                |m: &mut TorchTensor| { &mut m.size },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint32>(
                "owned",
                |m: &TorchTensor| { &m.owned },
                |m: &mut TorchTensor| { &mut m.owned },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt32>(
                "nr_dims",
                |m: &TorchTensor| { &m.nr_dims },
                |m: &mut TorchTensor| { &mut m.nr_dims },
            ));
            fields.push(::protobuf::reflect::accessor::make_vec_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                "dims",
                |m: &TorchTensor| { &m.dims },
                |m: &mut TorchTensor| { &mut m.dims },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeEnum<TorchDataType>>(
                "type",
                |m: &TorchTensor| { &m.field_type },
                |m: &mut TorchTensor| { &mut m.field_type },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<TorchTensor>(
                "TorchTensor",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static TorchTensor {
        static instance: ::protobuf::rt::LazyV2<TorchTensor> = ::protobuf::rt::LazyV2::INIT;
        instance.get(TorchTensor::new)
    }
}

impl ::protobuf::Clear for TorchTensor {
    fn clear(&mut self) {
        self.data.clear();
        self.size = 0;
        self.owned = 0;
        self.nr_dims = 0;
        self.dims.clear();
        self.field_type = TorchDataType::UNUSED;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for TorchTensor {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for TorchTensor {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct TorchModelRunRequest {
    // message fields
    pub session_id: u32,
    pub model_id: i64,
    pub run_options: ::std::vec::Vec<u8>,
    pub in_tensors: ::protobuf::RepeatedField<TorchTensor>,
    pub out_tensors: ::protobuf::RepeatedField<TorchTensor>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a TorchModelRunRequest {
    fn default() -> &'a TorchModelRunRequest {
        <TorchModelRunRequest as ::protobuf::Message>::default_instance()
    }
}

impl TorchModelRunRequest {
    pub fn new() -> TorchModelRunRequest {
        ::std::default::Default::default()
    }

    // uint32 session_id = 1;


    pub fn get_session_id(&self) -> u32 {
        self.session_id
    }
    pub fn clear_session_id(&mut self) {
        self.session_id = 0;
    }

    // Param is passed by value, moved
    pub fn set_session_id(&mut self, v: u32) {
        self.session_id = v;
    }

    // int64 model_id = 2;


    pub fn get_model_id(&self) -> i64 {
        self.model_id
    }
    pub fn clear_model_id(&mut self) {
        self.model_id = 0;
    }

    // Param is passed by value, moved
    pub fn set_model_id(&mut self, v: i64) {
        self.model_id = v;
    }

    // bytes run_options = 3;


    pub fn get_run_options(&self) -> &[u8] {
        &self.run_options
    }
    pub fn clear_run_options(&mut self) {
        self.run_options.clear();
    }

    // Param is passed by value, moved
    pub fn set_run_options(&mut self, v: ::std::vec::Vec<u8>) {
        self.run_options = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_run_options(&mut self) -> &mut ::std::vec::Vec<u8> {
        &mut self.run_options
    }

    // Take field
    pub fn take_run_options(&mut self) -> ::std::vec::Vec<u8> {
        ::std::mem::replace(&mut self.run_options, ::std::vec::Vec::new())
    }

    // repeated .vaccel.TorchTensor in_tensors = 4;


    pub fn get_in_tensors(&self) -> &[TorchTensor] {
        &self.in_tensors
    }
    pub fn clear_in_tensors(&mut self) {
        self.in_tensors.clear();
    }

    // Param is passed by value, moved
    pub fn set_in_tensors(&mut self, v: ::protobuf::RepeatedField<TorchTensor>) {
        self.in_tensors = v;
    }

    // Mutable pointer to the field.
    pub fn mut_in_tensors(&mut self) -> &mut ::protobuf::RepeatedField<TorchTensor> {
        &mut self.in_tensors
    }

    // Take field
    pub fn take_in_tensors(&mut self) -> ::protobuf::RepeatedField<TorchTensor> {
        ::std::mem::replace(&mut self.in_tensors, ::protobuf::RepeatedField::new())
    }

    // repeated .vaccel.TorchTensor out_tensors = 5;


    pub fn get_out_tensors(&self) -> &[TorchTensor] {
        &self.out_tensors
    }
    pub fn clear_out_tensors(&mut self) {
        self.out_tensors.clear();
    }

    // Param is passed by value, moved
    pub fn set_out_tensors(&mut self, v: ::protobuf::RepeatedField<TorchTensor>) {
        self.out_tensors = v;
    }

    // Mutable pointer to the field.
    pub fn mut_out_tensors(&mut self) -> &mut ::protobuf::RepeatedField<TorchTensor> {
        &mut self.out_tensors
    }

    // Take field
    pub fn take_out_tensors(&mut self) -> ::protobuf::RepeatedField<TorchTensor> {
        ::std::mem::replace(&mut self.out_tensors, ::protobuf::RepeatedField::new())
    }
}

impl ::protobuf::Message for TorchModelRunRequest {
    fn is_initialized(&self) -> bool {
        for v in &self.in_tensors {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.out_tensors {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint32()?;
                    self.session_id = tmp;
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int64()?;
                    self.model_id = tmp;
                },
                3 => {
                    ::protobuf::rt::read_singular_proto3_bytes_into(wire_type, is, &mut self.run_options)?;
                },
                4 => {
                    ::protobuf::rt::read_repeated_message_into(wire_type, is, &mut self.in_tensors)?;
                },
                5 => {
                    ::protobuf::rt::read_repeated_message_into(wire_type, is, &mut self.out_tensors)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.session_id != 0 {
            my_size += ::protobuf::rt::value_size(1, self.session_id, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.model_id != 0 {
            my_size += ::protobuf::rt::value_size(2, self.model_id, ::protobuf::wire_format::WireTypeVarint);
        }
        if !self.run_options.is_empty() {
            my_size += ::protobuf::rt::bytes_size(3, &self.run_options);
        }
        for value in &self.in_tensors {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        };
        for value in &self.out_tensors {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if self.session_id != 0 {
            os.write_uint32(1, self.session_id)?;
        }
        if self.model_id != 0 {
            os.write_int64(2, self.model_id)?;
        }
        if !self.run_options.is_empty() {
            os.write_bytes(3, &self.run_options)?;
        }
        for v in &self.in_tensors {
            os.write_tag(4, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        };
        for v in &self.out_tensors {
            os.write_tag(5, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        };
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> TorchModelRunRequest {
        TorchModelRunRequest::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint32>(
                "session_id",
                |m: &TorchModelRunRequest| { &m.session_id },
                |m: &mut TorchModelRunRequest| { &mut m.session_id },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt64>(
                "model_id",
                |m: &TorchModelRunRequest| { &m.model_id },
                |m: &mut TorchModelRunRequest| { &mut m.model_id },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                "run_options",
                |m: &TorchModelRunRequest| { &m.run_options },
                |m: &mut TorchModelRunRequest| { &mut m.run_options },
            ));
            fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<TorchTensor>>(
                "in_tensors",
                |m: &TorchModelRunRequest| { &m.in_tensors },
                |m: &mut TorchModelRunRequest| { &mut m.in_tensors },
            ));
            fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<TorchTensor>>(
                "out_tensors",
                |m: &TorchModelRunRequest| { &m.out_tensors },
                |m: &mut TorchModelRunRequest| { &mut m.out_tensors },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<TorchModelRunRequest>(
                "TorchModelRunRequest",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static TorchModelRunRequest {
        static instance: ::protobuf::rt::LazyV2<TorchModelRunRequest> = ::protobuf::rt::LazyV2::INIT;
        instance.get(TorchModelRunRequest::new)
    }
}

impl ::protobuf::Clear for TorchModelRunRequest {
    fn clear(&mut self) {
        self.session_id = 0;
        self.model_id = 0;
        self.run_options.clear();
        self.in_tensors.clear();
        self.out_tensors.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for TorchModelRunRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for TorchModelRunRequest {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct JitloadForwardResult {
    // message fields
    pub out_tensors: ::protobuf::RepeatedField<TorchTensor>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a JitloadForwardResult {
    fn default() -> &'a JitloadForwardResult {
        <JitloadForwardResult as ::protobuf::Message>::default_instance()
    }
}

impl JitloadForwardResult {
    pub fn new() -> JitloadForwardResult {
        ::std::default::Default::default()
    }

    // repeated .vaccel.TorchTensor out_tensors = 1;


    pub fn get_out_tensors(&self) -> &[TorchTensor] {
        &self.out_tensors
    }
    pub fn clear_out_tensors(&mut self) {
        self.out_tensors.clear();
    }

    // Param is passed by value, moved
    pub fn set_out_tensors(&mut self, v: ::protobuf::RepeatedField<TorchTensor>) {
        self.out_tensors = v;
    }

    // Mutable pointer to the field.
    pub fn mut_out_tensors(&mut self) -> &mut ::protobuf::RepeatedField<TorchTensor> {
        &mut self.out_tensors
    }

    // Take field
    pub fn take_out_tensors(&mut self) -> ::protobuf::RepeatedField<TorchTensor> {
        ::std::mem::replace(&mut self.out_tensors, ::protobuf::RepeatedField::new())
    }
}

impl ::protobuf::Message for JitloadForwardResult {
    fn is_initialized(&self) -> bool {
        for v in &self.out_tensors {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_repeated_message_into(wire_type, is, &mut self.out_tensors)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        for value in &self.out_tensors {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        for v in &self.out_tensors {
            os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        };
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> JitloadForwardResult {
        JitloadForwardResult::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<TorchTensor>>(
                "out_tensors",
                |m: &JitloadForwardResult| { &m.out_tensors },
                |m: &mut JitloadForwardResult| { &mut m.out_tensors },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<JitloadForwardResult>(
                "JitloadForwardResult",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static JitloadForwardResult {
        static instance: ::protobuf::rt::LazyV2<JitloadForwardResult> = ::protobuf::rt::LazyV2::INIT;
        instance.get(JitloadForwardResult::new)
    }
}

impl ::protobuf::Clear for JitloadForwardResult {
    fn clear(&mut self) {
        self.out_tensors.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for JitloadForwardResult {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for JitloadForwardResult {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct TorchModelRunResponse {
    // message oneof groups
    pub result: ::std::option::Option<TorchModelRunResponse_oneof_result>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a TorchModelRunResponse {
    fn default() -> &'a TorchModelRunResponse {
        <TorchModelRunResponse as ::protobuf::Message>::default_instance()
    }
}

#[derive(Clone,PartialEq,Debug)]
pub enum TorchModelRunResponse_oneof_result {
    error(super::error::VaccelError),
    result(JitloadForwardResult),
}

impl TorchModelRunResponse {
    pub fn new() -> TorchModelRunResponse {
        ::std::default::Default::default()
    }

    // .vaccel.VaccelError error = 1;


    pub fn get_error(&self) -> &super::error::VaccelError {
        match self.result {
            ::std::option::Option::Some(TorchModelRunResponse_oneof_result::error(ref v)) => v,
            _ => <super::error::VaccelError as ::protobuf::Message>::default_instance(),
        }
    }
    pub fn clear_error(&mut self) {
        self.result = ::std::option::Option::None;
    }

    pub fn has_error(&self) -> bool {
        match self.result {
            ::std::option::Option::Some(TorchModelRunResponse_oneof_result::error(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_error(&mut self, v: super::error::VaccelError) {
        self.result = ::std::option::Option::Some(TorchModelRunResponse_oneof_result::error(v))
    }

    // Mutable pointer to the field.
    pub fn mut_error(&mut self) -> &mut super::error::VaccelError {
        if let ::std::option::Option::Some(TorchModelRunResponse_oneof_result::error(_)) = self.result {
        } else {
            self.result = ::std::option::Option::Some(TorchModelRunResponse_oneof_result::error(super::error::VaccelError::new()));
        }
        match self.result {
            ::std::option::Option::Some(TorchModelRunResponse_oneof_result::error(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_error(&mut self) -> super::error::VaccelError {
        if self.has_error() {
            match self.result.take() {
                ::std::option::Option::Some(TorchModelRunResponse_oneof_result::error(v)) => v,
                _ => panic!(),
            }
        } else {
            super::error::VaccelError::new()
        }
    }

    // .vaccel.JitloadForwardResult result = 2;


    pub fn get_result(&self) -> &JitloadForwardResult {
        match self.result {
            ::std::option::Option::Some(TorchModelRunResponse_oneof_result::result(ref v)) => v,
            _ => <JitloadForwardResult as ::protobuf::Message>::default_instance(),
        }
    }
    pub fn clear_result(&mut self) {
        self.result = ::std::option::Option::None;
    }

    pub fn has_result(&self) -> bool {
        match self.result {
            ::std::option::Option::Some(TorchModelRunResponse_oneof_result::result(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_result(&mut self, v: JitloadForwardResult) {
        self.result = ::std::option::Option::Some(TorchModelRunResponse_oneof_result::result(v))
    }

    // Mutable pointer to the field.
    pub fn mut_result(&mut self) -> &mut JitloadForwardResult {
        if let ::std::option::Option::Some(TorchModelRunResponse_oneof_result::result(_)) = self.result {
        } else {
            self.result = ::std::option::Option::Some(TorchModelRunResponse_oneof_result::result(JitloadForwardResult::new()));
        }
        match self.result {
            ::std::option::Option::Some(TorchModelRunResponse_oneof_result::result(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_result(&mut self) -> JitloadForwardResult {
        if self.has_result() {
            match self.result.take() {
                ::std::option::Option::Some(TorchModelRunResponse_oneof_result::result(v)) => v,
                _ => panic!(),
            }
        } else {
            JitloadForwardResult::new()
        }
    }
}

impl ::protobuf::Message for TorchModelRunResponse {
    fn is_initialized(&self) -> bool {
        if let Some(TorchModelRunResponse_oneof_result::error(ref v)) = self.result {
            if !v.is_initialized() {
                return false;
            }
        }
        if let Some(TorchModelRunResponse_oneof_result::result(ref v)) = self.result {
            if !v.is_initialized() {
                return false;
            }
        }
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.result = ::std::option::Option::Some(TorchModelRunResponse_oneof_result::error(is.read_message()?));
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.result = ::std::option::Option::Some(TorchModelRunResponse_oneof_result::result(is.read_message()?));
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let ::std::option::Option::Some(ref v) = self.result {
            match v {
                &TorchModelRunResponse_oneof_result::error(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
                },
                &TorchModelRunResponse_oneof_result::result(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
                },
            };
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if let ::std::option::Option::Some(ref v) = self.result {
            match v {
                &TorchModelRunResponse_oneof_result::error(ref v) => {
                    os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
                    os.write_raw_varint32(v.get_cached_size())?;
                    v.write_to_with_cached_sizes(os)?;
                },
                &TorchModelRunResponse_oneof_result::result(ref v) => {
                    os.write_tag(2, ::protobuf::wire_format::WireTypeLengthDelimited)?;
                    os.write_raw_varint32(v.get_cached_size())?;
                    v.write_to_with_cached_sizes(os)?;
                },
            };
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> TorchModelRunResponse {
        TorchModelRunResponse::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_singular_message_accessor::<_, super::error::VaccelError>(
                "error",
                TorchModelRunResponse::has_error,
                TorchModelRunResponse::get_error,
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_message_accessor::<_, JitloadForwardResult>(
                "result",
                TorchModelRunResponse::has_result,
                TorchModelRunResponse::get_result,
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<TorchModelRunResponse>(
                "TorchModelRunResponse",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static TorchModelRunResponse {
        static instance: ::protobuf::rt::LazyV2<TorchModelRunResponse> = ::protobuf::rt::LazyV2::INIT;
        instance.get(TorchModelRunResponse::new)
    }
}

impl ::protobuf::Clear for TorchModelRunResponse {
    fn clear(&mut self) {
        self.result = ::std::option::Option::None;
        self.result = ::std::option::Option::None;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for TorchModelRunResponse {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for TorchModelRunResponse {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(Clone,PartialEq,Eq,Debug,Hash)]
pub enum TorchDataType {
    UNUSED = 0,
    FLOAT = 1,
    DOUBLE = 2,
    INT32 = 3,
    UINT8 = 4,
    INT16 = 5,
    INT8 = 6,
    STRING = 7,
    COMPLEX = 8,
    INT64 = 9,
    BOOL = 10,
    QINT8 = 11,
    QUINT8 = 12,
    QINT32 = 13,
    BFLOAT16 = 14,
    QINT16 = 15,
    QUINT16 = 16,
    UINT16 = 17,
    COMPLEX128 = 18,
    HALF = 19,
    RESOURCE = 20,
    VARIANT = 21,
    UINT32 = 22,
    UINT64 = 23,
}

impl ::protobuf::ProtobufEnum for TorchDataType {
    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<TorchDataType> {
        match value {
            0 => ::std::option::Option::Some(TorchDataType::UNUSED),
            1 => ::std::option::Option::Some(TorchDataType::FLOAT),
            2 => ::std::option::Option::Some(TorchDataType::DOUBLE),
            3 => ::std::option::Option::Some(TorchDataType::INT32),
            4 => ::std::option::Option::Some(TorchDataType::UINT8),
            5 => ::std::option::Option::Some(TorchDataType::INT16),
            6 => ::std::option::Option::Some(TorchDataType::INT8),
            7 => ::std::option::Option::Some(TorchDataType::STRING),
            8 => ::std::option::Option::Some(TorchDataType::COMPLEX),
            9 => ::std::option::Option::Some(TorchDataType::INT64),
            10 => ::std::option::Option::Some(TorchDataType::BOOL),
            11 => ::std::option::Option::Some(TorchDataType::QINT8),
            12 => ::std::option::Option::Some(TorchDataType::QUINT8),
            13 => ::std::option::Option::Some(TorchDataType::QINT32),
            14 => ::std::option::Option::Some(TorchDataType::BFLOAT16),
            15 => ::std::option::Option::Some(TorchDataType::QINT16),
            16 => ::std::option::Option::Some(TorchDataType::QUINT16),
            17 => ::std::option::Option::Some(TorchDataType::UINT16),
            18 => ::std::option::Option::Some(TorchDataType::COMPLEX128),
            19 => ::std::option::Option::Some(TorchDataType::HALF),
            20 => ::std::option::Option::Some(TorchDataType::RESOURCE),
            21 => ::std::option::Option::Some(TorchDataType::VARIANT),
            22 => ::std::option::Option::Some(TorchDataType::UINT32),
            23 => ::std::option::Option::Some(TorchDataType::UINT64),
            _ => ::std::option::Option::None
        }
    }

    fn values() -> &'static [Self] {
        static values: &'static [TorchDataType] = &[
            TorchDataType::UNUSED,
            TorchDataType::FLOAT,
            TorchDataType::DOUBLE,
            TorchDataType::INT32,
            TorchDataType::UINT8,
            TorchDataType::INT16,
            TorchDataType::INT8,
            TorchDataType::STRING,
            TorchDataType::COMPLEX,
            TorchDataType::INT64,
            TorchDataType::BOOL,
            TorchDataType::QINT8,
            TorchDataType::QUINT8,
            TorchDataType::QINT32,
            TorchDataType::BFLOAT16,
            TorchDataType::QINT16,
            TorchDataType::QUINT16,
            TorchDataType::UINT16,
            TorchDataType::COMPLEX128,
            TorchDataType::HALF,
            TorchDataType::RESOURCE,
            TorchDataType::VARIANT,
            TorchDataType::UINT32,
            TorchDataType::UINT64,
        ];
        values
    }

    fn enum_descriptor_static() -> &'static ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            ::protobuf::reflect::EnumDescriptor::new_pb_name::<TorchDataType>("TorchDataType", file_descriptor_proto())
        })
    }
}

impl ::std::marker::Copy for TorchDataType {
}

impl ::std::default::Default for TorchDataType {
    fn default() -> Self {
        TorchDataType::UNUSED
    }
}

impl ::protobuf::reflect::ProtobufValue for TorchDataType {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Enum(::protobuf::ProtobufEnum::descriptor(self))
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x0btorch.proto\x12\x06vaccel\x1a\x0berror.proto\"W\n\x15TorchModelLoa\
    dRequest\x12\x1f\n\nsession_id\x18\x01\x20\x01(\rR\tsessionIdB\0\x12\x1b\
    \n\x08model_id\x18\x02\x20\x01(\x03R\x07modelIdB\0:\0\"t\n\x16TorchModel\
    LoadResponse\x12\x1f\n\tgraph_def\x18\x01\x20\x01(\x0cH\0R\x08graphDefB\
    \0\x12-\n\x05error\x18\x02\x20\x01(\x0b2\x13.vaccel.VaccelErrorH\0R\x05e\
    rrorB\0B\x08\n\x06result:\0\"Y\n\x17TorchModelUnloadRequest\x12\x1f\n\ns\
    ession_id\x18\x01\x20\x01(\rR\tsessionIdB\0\x12\x1b\n\x08model_id\x18\
    \x02\x20\x01(\x03R\x07modelIdB\0:\0\"e\n\x18TorchModelUnloadResponse\x12\
    \x1a\n\x07success\x18\x01\x20\x01(\x08R\x07successB\0\x12+\n\x05error\
    \x18\x02\x20\x01(\x0b2\x13.vaccel.VaccelErrorR\x05errorB\0:\0\"\xb1\x01\
    \n\x0bTorchTensor\x12\x14\n\x04data\x18\x01\x20\x01(\x0cR\x04dataB\0\x12\
    \x14\n\x04size\x18\x02\x20\x01(\x04R\x04sizeB\0\x12\x16\n\x05owned\x18\
    \x03\x20\x01(\rR\x05ownedB\0\x12\x19\n\x07nr_dims\x18\x04\x20\x01(\x05R\
    \x06nrDimsB\0\x12\x14\n\x04dims\x18\x05\x20\x03(\x04R\x04dimsB\0\x12+\n\
    \x04type\x18\x06\x20\x01(\x0e2\x15.vaccel.TorchDataTypeR\x04typeB\0:\0\"\
    \xe7\x01\n\x14TorchModelRunRequest\x12\x1f\n\nsession_id\x18\x01\x20\x01\
    (\rR\tsessionIdB\0\x12\x1b\n\x08model_id\x18\x02\x20\x01(\x03R\x07modelI\
    dB\0\x12!\n\x0brun_options\x18\x03\x20\x01(\x0cR\nrunOptionsB\0\x124\n\n\
    in_tensors\x18\x04\x20\x03(\x0b2\x13.vaccel.TorchTensorR\tinTensorsB\0\
    \x126\n\x0bout_tensors\x18\x05\x20\x03(\x0b2\x13.vaccel.TorchTensorR\nou\
    tTensorsB\0:\0\"P\n\x14JitloadForwardResult\x126\n\x0bout_tensors\x18\
    \x01\x20\x03(\x0b2\x13.vaccel.TorchTensorR\noutTensorsB\0:\0\"\x8c\x01\n\
    \x15TorchModelRunResponse\x12-\n\x05error\x18\x01\x20\x01(\x0b2\x13.vacc\
    el.VaccelErrorH\0R\x05errorB\0\x128\n\x06result\x18\x02\x20\x01(\x0b2\
    \x1c.vaccel.JitloadForwardResultH\0R\x06resultB\0B\x08\n\x06result:\0*\
    \xb0\x02\n\rTorchDataType\x12\n\n\x06UNUSED\x10\0\x12\t\n\x05FLOAT\x10\
    \x01\x12\n\n\x06DOUBLE\x10\x02\x12\t\n\x05INT32\x10\x03\x12\t\n\x05UINT8\
    \x10\x04\x12\t\n\x05INT16\x10\x05\x12\x08\n\x04INT8\x10\x06\x12\n\n\x06S\
    TRING\x10\x07\x12\x0b\n\x07COMPLEX\x10\x08\x12\t\n\x05INT64\x10\t\x12\
    \x08\n\x04BOOL\x10\n\x12\t\n\x05QINT8\x10\x0b\x12\n\n\x06QUINT8\x10\x0c\
    \x12\n\n\x06QINT32\x10\r\x12\x0c\n\x08BFLOAT16\x10\x0e\x12\n\n\x06QINT16\
    \x10\x0f\x12\x0b\n\x07QUINT16\x10\x10\x12\n\n\x06UINT16\x10\x11\x12\x0e\
    \n\nCOMPLEX128\x10\x12\x12\x08\n\x04HALF\x10\x13\x12\x0c\n\x08RESOURCE\
    \x10\x14\x12\x0b\n\x07VARIANT\x10\x15\x12\n\n\x06UINT32\x10\x16\x12\n\n\
    \x06UINT64\x10\x17\x1a\0B\0b\x06proto3\
";

static file_descriptor_proto_lazy: ::protobuf::rt::LazyV2<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::LazyV2::INIT;

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    file_descriptor_proto_lazy.get(|| {
        parse_descriptor_proto()
    })
}
